### ISSUE TITLE
Outdated dynamic library code

### ISSUE THREAD

**Issue by VijaiCPrasad** [shubham0204/Sentence-Embeddings-Android#9]
Seems like the libs branch has not been updated with the latest dynamic library. 
The result struct is missing `token_type_ids` which is not the case with the prebuilt library from `3-support-more-embedding-models` branch. 
```
struct TokenizationResult {
    ids: Vec<u32>,
    attention_mask: Vec<u32>,
}
```

**Comment by shubham0204** [comment]
Thank you for pointing out @VijaiCPrasad! The `libs` branch has been updated with the latest code for the dynamic library.
